dataset: 'scannet'
meshing:
  resolution: 0.02 #cm # Increase this number to speed up meshing algorithm
  eval_rec: False
tracking:
  ignore_edge_W: 20
  ignore_edge_H: 20
  lr_T: 0.0015
  lr_R: 0.0025
  pixels: 1000
  iters: 10
mapping:
  pixels: 2000
  iters: 10
  every_frame: 5
  keyframe_every: 5
  map_expand_size: 1.5
  map_allo_threshold: 0.25
  BA: True
  bundle_frames: 40
cam: 
  H: 480 
  W: 640
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609
  png_depth_scale: 1000. #for depth image in png format
  crop_edge: 10
rendering:
  n_stratified: 32
  n_importance: 12
  learnable_beta: True
