dataset: 'scannet'
meshing:
  resolution: 0.02 #cm # Increase this number to speed up meshing algorithm
  eval_rec: False
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  lr_T: 0.0005
  lr_R: 0.0025
  pixels: 1024
  iters: 10
mapping:
  pixels: 3200
  iters: 15
  keyframe_every: 2
cam: 
  H: 480 
  W: 640
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609
  png_depth_scale: 1000. #for depth image in png format
  crop_edge: 10
rendering:
  n_stratified: 32
  n_importance: 12
  learnable_beta: True
