dataset: 'azure'
tracking:
  vis_freq: 100000
  vis_inside_freq: 250000
  ignore_edge_W: 20
  ignore_edge_H: 20
  const_speed_assumption: True
  lr_T: 0.0015
  lr_R: 0.0025
  pixels: 1000
  iters: 10
mapping:
  every_frame: 5
  vis_freq: 500000
  vis_inside_freq: 300000
  mesh_freq: 100000
  ckpt_freq: 100000
  keyframe_every: 10
  mapping_window_size: 10
  pixels: 2000
  iters_first: 1000
  iters: 10
  map_expand_size: 2.5
  map_allo_threshold: 0.2
  BA: True
  bundle_frames: 40
cam:
  H: 720 
  W: 1280
  fx: 607.4694213867188
  fy: 607.4534912109375
  cx: 636.9967041015625
  cy: 369.2689514160156
  png_depth_scale: 1000.0 #for depth image in png format
  crop_edge: 0
data:
  input_folder: Datasets/Apartment
  output: output/Apartment/2
meshing:
  resolution: 0.02
  marching_cubes_bound: [[-5.8,11.3],[-4.0,4.5],[-7.9,4.9]]
rendering:
  n_stratified: 32
  n_importance: 12
  learnable_beta: True
