inherit_from: configs/TUM_RGBD/tum.yaml
data:
  input_folder: Datasets/TUM_RGBD/rgbd_dataset_freiburg2_xyz
  output: output/TUM_RGBD/rgbd_dataset_freiburg2_xyz/6
cam:  #intrinsic is different per scene in TUM
  H: 480
  W: 640
  fx: 520.9
  fy: 521.0
  cx: 325.1
  cy: 249.7
  crop_edge: 8
  crop_size: [384,512]
  distortion: [0.2312, -0.7849, -0.0033, -0.0001, 0.9172]
