inherit_from: configs/Replica/replica.yaml
mapping:
  #bound: [[-1.9,7.9],[-2.2,4.5],[-2.5,2.3]]
  bound: [[-3,9],[-3,6],[-3,3]]
  #marching_cubes_bound: [[-1.9,7.9],[-2.2,4.5],[-2.5,2.3]]
  marching_cubes_bound: [[-3,9],[-3,6],[-3,3]]
data:
  input_folder: ../myslam_submapping/Datasets/Replica/room0
  output: output/Replica/room0
