dataset: 'kinect'
tracking:
  vis_freq: 100000
  vis_inside_freq: 250000
  ignore_edge_W: 20
  ignore_edge_H: 20
  const_speed_assumption: True
  lr_T: 0.01
  lr_R: 0.002
  pixels: 2000
  iters: 20
mapping:
  every_frame: 5
  vis_freq: 500000
  vis_inside_freq: 300000
  mesh_freq: 100000
  ckpt_freq: 100000
  keyframe_every: 20
  mapping_window_size: 10
  pixels: 2000
  iters_first: 1000
  iters: 10
  map_expand_size: 2
  map_allo_threshold: 0.2
  BA: True
  bundle_frames: 40
cam:
  H: 424
  W: 512
  fx: 370.04669189453125
  fy: 370.04669189453125
  cx: 258.6017150878906
  cy: 207.4394989013672
  png_depth_scale: 1.0 #for depth image in png format
  crop_edge: 0
data:
  input_folder: Datasets/data_504
  output: output/504
meshing:
  resolution: 0.02
rendering:
  n_stratified: 32
  n_importance: 8
  learnable_beta: False
